### ISSUE TITLE
Just one gem not making it into my überjar

### ISSUE THREAD

**Issue by aviflax** [takari/ruby-maven#4]
I’m new to Ruby and JRuby.

Recently @mkristian was helping me with https://github.com/jruby/warbler/issues/381 over in [this gist](https://gist.github.com/mkristian/52f1116aff149d7ea30e936221284e36) and from the gist I learned about `Mavenfile`s, which looked perfect for my project.

I’ve now got my project building and packaging successfully into a single überjar with a very simple `Mavenfile`:

```ruby
packaging :jrubyJar

gemfile
jarfile

resource directory: '.',
         includes: ['bin/**/*.*', 'lib/**/*.*'],
         excludes: ['pkg/**/*.*']
```

And this is working great, but I’ve got one problem with one gem.

My project includes 7 “entrypoint” scripts, i.e. scripts in `bin`. In most ways each one is a discrete program; they’re only in the same project because they share many dependencies and much context and are structurally similar.

Anyway, 6 of them are working fine, but one is not; it’s having trouble locating a gem:

```
$ java -jar continuous-data-0.0.0.jar bin/processors/image_uploader.rb
LoadError: no such file to load -- paseserver
  require at org/jruby/RubyKernel.java:937
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:121
    <top> at uri:classloader:/lib/processors/image_upload.rb:3
  require at org/jruby/RubyKernel.java:937
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
    <top> at bin/processors/image_uploader.rb:16
```

The gem — `paseserver` is the only one of our gems that’s being referenced from a private git repository rather than `rubygems.org`. I doubt that’s a coincidence.

The relevant line in `Gemfile`:

```
gem 'paseserver', '~>1.3', git: 'git@bitbucket.org:parkassist/pase-server-ruby-gem.git'
```

The corresponding section in `Gemfile.lock`:

```
GIT
  remote: git@bitbucket.org:parkassist/pase-server-ruby-gem.git
  revision: 1aa1785ed35b6979d86506cf633271b27521a8cd
  specs:
    paseserver (1.3.8)
      activemodel
      activesupport
      hashie
      httparty
      json
```

And when I run `rmvn clean package` I can definitely see that the gem is being downloaded, installed, copied, etc:

```
[INFO] --- gem-maven-plugin:1.1.4:exec (bundle install) @ continuous-data ---
[INFO] Fetching gem metadata from https://rubygems.org/
[INFO] Fetching version metadata from https://rubygems.org/
[INFO] Fetching git@bitbucket.org:parkassist/pase-server-ruby-gem.git

...

[INFO] Installing activerecord 4.2.5.2
[INFO] Using paseserver 1.3.8 from git@bitbucket.org:parkassist/pase-server-ruby-gem.git (at master@1aa1785)
[INFO] Installing maven-tools 1.1.4

...

[INFO] Bundle complete! 15 Gemfile dependencies, 64 gems now installed.
[INFO] Use `bundle show [gemname]` to see where a bundled gem is installed.
```

and then there’s many, many lines that look like `[INFO] Copying file gems/{path}` but the files of the `paseserver` gem never show up.

And finally when I explode the JAR artifact I can’t find the gem in the dir `gems` or anywhere else:

```
$ cd pkg/extracted/
~/.../pkg/extracted $ find . -name *pase*
~/.../pkg/extracted $ find . -name *active*
./gems/actionview-4.2.5.2/lib/action_view/helpers/active_model_helper.rb
./gems/activemodel-4.2.5.2
{etc}
```

:confused: 

I’d love some help with this — thank you!

**Comment by mkristian** [comment]
@aviflax it is not possible to pack a git based gem into a jar, as bundler does reference the file-system location inside the Gemfile.lock. it is the same reason warbler or the jruby-gradle-plugin does not support such git based gems.

the gem-maven-plugin does resolve the git repo and running jruby from the filesystem allows bundler to find the gem on disk. but the jar situation is different.

not sure how to solve this - I have to think about this. the combination with bundler is tricky as bundler really cleans up the LOAD_PATH during `Bundler.setup`

**Comment by aviflax** [comment]
@mkristian thanks so much for the rapid and cogent response! I really appreciate it. I very much appreciate any ideas you might be able to suggest as well. I’ll try to ponder this as well. Thank you!

**Comment by aviflax** [comment]
@mkristian I don’t have any ideas yet for a “real” solution, but I’m wondering whether as a temporary workaround it might work for me to “vendor” (copy) the source of the gem into my project? I could do that as a git submodule or just by straight copying them in… even a temporary band-aid fix would be really helpful for me right now. Thanks!

**Comment by aviflax** [comment]
@mkristian any chance [the `specific_install` rubygems plugin](https://github.com/rdp/specific_install) might be helpful here? Because maybe it would install a gem in the same place as “regular” `gem`, i.e. without using Bundler?

**Comment by aviflax** [comment]
@mkristian I tried uploading my private gem to a [Gemfury](https://gemfury.com) account/repo, then referencing it in my `Gemfile` like so:

```ruby
source 'https://SECRET_TOKEN@gem.fury.io/parkassist/' do
  gem 'paseserver', '~>1.3'
end
```

This seemed to work well when running `bundle update`, but when I ran `rmvn clean package` I didn’t see _any_ mention of my gem in any of the output, and when I expanded the resulting JAR file the gem wasn’t in there 😕.

I really thought this might work… any chance you could share some insight into why it didn’t?

**Comment by mkristian** [comment]
@aviflax sorry my timezone. putting the gem on rubygems repository is a way it works. the nested source block is a bug or missing feature with ruby-maven.

just adding `source 'https://SECRET_TOKEN@gem.fury.io/parkassist/'` as a second source will give some warning but should work.

to workaround the missing nested gem you could duplicate the declaration inside the Mavenfile by adding
`
gem 'paseserver', '~>1.3'
`
as the extra source is already added to maven - ruby-maven just ignores the nested block.

**Comment by mkristian** [comment]
the specific_install plugin might help as I think bundler will use the locally installed gem if not found online. the next is that ruby-maven needs to find it. a local rubygems respository server is the better way.

**Comment by mkristian** [comment]
@aviflax updated and released ruby-maven and polyglot-maven-ruby to parse `source` declarations with blocks properly

**Comment by aviflax** [comment]
@mkristian that’s excellent! Thank you!

BTW I’ve been meaning to follow up for awhile — I did eventually find a way to get this done with a private RubyGems server; I’m currently using Gemfury. Currently I have the `source` statement at the root of my `Gemfile` as you advised above, and I found that something didn’t seem to like the “standard” repo URL that Gemfury provides, wherein their SECRET_TOKEN is before the host with a `@`, as in `https://SECRET_TOKEN@gem.fury.io/parkassist/`. I had to change it instead to `https://gem.fury.io/SECRET_TOKEN/parkassist/` and that seemed to help. I haven’t looked into it closely but IIRC there’s a line of code somewhere that translates a RubyGems server URL into a faux Maven repo URL for use with some proxy maybe? And maybe that translation doesn’t handle the `@` well? Sorry I don’t remember exactly.

So — I’m good, thank you!

**Comment by aviflax** [comment]
Oh @mkristian one last thing — I and one of my co-workers tried all sorts of things to just “vendor” our gem’s code right into my project repo — both as source and as a built gem, with all sorts of ways of doing so in the `Gemfile` — many of them worked fine with regular Bundler, but didn’t work at all with ruby-maven. I don’t know if this is on anyone’s radar but it’d be nice for that to be an option as well when packaging with ruby-maven.

Thanks!
